version: '3.1'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    networks:
      zabbix-cluster:
        ipv4_address: 10.5.0.2

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    environment:
      ZBX_DEBUGLEVEL: 3
      DB_SERVER_HOST: "postgres"
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    networks:
      zabbix-cluster:
        ipv4_address: 10.5.0.3
    depends_on:
      - postgres

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_POSTMAXSIZE: 64M
      ZBX_MAXEXECUTIONTIME: 500
      DB_SERVER_HOST: "postgres"
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      PHP_TZ: "America/Sao_Paulo"
    networks:
      zabbix-cluster:
        ipv4_address: 10.5.0.4
    ports:
      - "8080:80"
    depends_on:
      - postgres

  client1:
    image: jeangnc/monitored-client:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      zabbix-cluster:
        ipv4_address: 10.5.0.100

  client2:
    image: jeangnc/monitored-client:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      zabbix-cluster:
        ipv4_address: 10.5.0.101

networks:
  zabbix-cluster:
    ipam:
      config:
        - subnet: 10.5.0.0/24
