version: '3.1'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    restart: always
    environment:
      ZBX_DEBUGLEVEL: 3
      DB_SERVER_HOST: "postgres"
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    ports:
      - "10052:10051"
    depends_on:
      - postgres

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    restart: always
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_POSTMAXSIZE: 64M
      ZBX_MAXEXECUTIONTIME: 500
      DB_SERVER_HOST: "postgres"
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      PHP_TZ: "America/Sao_Paulo"
    ports:
      - "8090:80"
    depends_on:
      - postgres
      - zabbix-server

  zabbix-proxy:
    image: zabbix/zabbix-proxy-sqlite3:latest
    network_mode: "host"
    restart: unless-stopped
    environment:
      ZBX_HOSTNAME: proxy1
      ZBX_SERVER_HOST: 127.0.0.1
      ZBX_SERVER_PORT: 10052
      ZBX_DEBUGLEVEL: 4
    ports:
      - "10051:10051"
    depends_on:
      - zabbix-server
